-- 코드를 작성해주세요
WITH PARENT AS (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
)
SELECT
    E.ID, GENOTYPE, PARENT_GENOTYPE
FROM
    ECOLI_DATA AS E
JOIN
    PARENT
ON
    PARENT.ID = E.PARENT_ID
WHERE
    (E.GENOTYPE & PARENT_GENOTYPE) >= PARENT_GENOTYPE
ORDER BY
    ID