-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
    AND CAR_ID IN (
    select car_id
    from car_rental_company_rental_history
    where START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    group by car_id
    having count(car_id) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH(START_DATE), CAR_ID DESC
