-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
JOIN (
    SELECT
        CATEGORY, MAX(PRICE) AS PRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
    HAVING
        CATEGORY IN ('과자', '국', '김치', '식용유')
) AS M
ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.PRICE
ORDER BY MAX_PRICE DESC
